### ISSUE TITLE
[Bug]: Google not indexing with this theme

### ISSUE THREAD

**Issue by avances123** [CaiJimmy/hugo-theme-stack#827] opened 2023-06-09 21:16 UTC
### What happened?

 I wanted to bring to your attention a critical issue we've been facing with our blog. We have been using the Stack theme for over six months, but unfortunately, it has resulted in the creation of multiple duplicate pages. Consequently, Google has been unable to index our blog.

It seems to be the meta tag description, which is repeated in every page.

### Hugo version

 0.112.7

### Theme version

3.16.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### More information about the browser

SEO problem

### Link to the page with bug

 https://buceo.avances123.es

**Comment by CaiJimmy** [comment] 2023-08-12 10:36
I'm not an expert in SEO optimization so I'm not sure where the problem is.

> It seems to be the meta tag description, which is repeated in every page.

I don't believe that's the problem. The description meta tag appears 3 times, but they are for different purposes:

- `og:description` (Opengraph)
- `twitter:description` (Twitter card)
- `description` (default, fallback)

**Comment by CaiJimmy** [comment] 2023-08-15 10:30
And Google seems to be indexing your site correctly:

![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/5889006/c78dd116-5623-41cd-9152-fe54b857b7d1)

Closing this issue for now. Feel free to reopen it if the problem still persists.

**Closed by CaiJimmy** 2023-08-15 10:30 UTC
Labels: question
