### ISSUE TITLE
更改特色图片(文章封面图)来自原图的位置

### ISSUE THREAD

**Issue by Weltolk** [CaiJimmy/hugo-theme-stack#499] opened 2022-02-16 15:04 UTC
**Is your feature request related to a problem? Please describe.**
无

**Describe the solution you'd like**
更改特色图片(文章封面图)来自原图的位置

**Describe alternatives you've considered**
无

**Additional context**
无

**Comment by CaiJimmy** [comment] 2022-02-19 06:30
Duplicate of https://github.com/CaiJimmy/hugo-theme-stack/issues/472

**Closed** 2022-02-19 06:30 UTC
