### ISSUE TITLE
[Bug]: #fnref (footnote reference) does not work

### ISSUE THREAD

**Issue by ttheng3810** [CaiJimmy/hugo-theme-stack#632] opened 2022-06-14 06:45 UTC
### What happened?

Hello, in the recent 3.12.0 version of the theme, I discovered that when I attempt to click on the arrow at the end of a footnote of a web page to look for the corresponding footnote reference in an article, it does not scroll back up properly as expected.

This worked before in the 3.11.0 version of the theme. How should I resolve this issue? Thanks!

### Hugo version

0.100.2

### Theme version

3.12.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### Link to the page with bug

https://demo.stack.jimmycai.com/p/markdown-syntax-guide/

**Comment by axelsegebrecht** [comment] 2022-06-16 12:52
Same issue here with hugo v0.100.2+extended linux/amd64 and in Brave/Chrome. The link is there but it doesn't skip back up (nor down to the footnote in fact):

Link back up
`<a href="#fnref:1" class="footnote-backref" role="doc-backlink">↩︎</a>`

I think this should be '#fnref1' instead of #fnref:1? Perhaps the ':' is messing with it.

Link to footnote
`<sup id="fnref:1"><a href="#fn:1" class="footnote-ref" role="doc-noteref">1</a></sup>`

**Comment by starmz123** [comment] 2022-07-22 21:00
Same here - it was working a day or so ago, so I'm somewhat confused as to why this is suddenly showing up!

**Comment by CaiJimmy** [comment] 2022-07-22 21:17
It's caused by this commit: https://github.com/CaiJimmy/hugo-theme-stack/commit/7142de24cc211d52a4db0bb88c7ed10748ab397d

Can be fixed by changing that line to:

```
            const target = document.getElementById(targetId) as HTMLElement;
```

I'm still investigating because there seems to be another issue underneath it.

**Closed** 2022-07-28 16:48 UTC
Labels: bug
