### ISSUE TITLE
Menu icon issue & How to open a new tab in Menu entry ?

### ISSUE THREAD

**Issue by Peckystudios** [CaiJimmy/hugo-theme-stack#218] opened 2021-06-03 09:47 UTC
Hi 
Thanks for designing a great-looking theme!

I try to add a menu entry to link my store.
I found that the icon I added doesn't change when I click other menus entry
Not sure if the format of SVG is wrong

![](https://i.imgur.com/ec4E6UU.png)

the other question is 

Can I let the menu entry open a new tab?

My page front matter:
![](https://i.imgur.com/RZrWXLS.png)

您好
謝謝你設計了很漂亮的主題！

我想要在主要菜單加入一個連往外部的連結
連結是有成功，但icon卻不會像其他menu一樣變換顏色
不確定是不是svg格式的差異?

另一個問題是有沒有方法可以讓menu開啟的時候在新分頁開啟呢？

## Environment

- **Hugo version** [e.g: 0.80.0]:  v0.83.1+extended darwin/arm64 BuildDate=unknown
- **Hugo extended?**: Yes / No : 

## Additional context

If it's a UI issue, fill the following information:

 - OS: [e.g. iOS]:Mac mini / Big Sur 11.2.3
 - Browser [e.g. chrome, safari] : Chrome

## Content of config.yaml
```yaml
baseurl: https://peckystudios.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Pecky studios

# Change it to your Disqus shortname before using
disqusShortname: peckystudios

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /img/branding/logo_tran-48x48.ico

    footer:
        since: 2021
        customText: Happy with my Blog.

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: ❤️
        subtitle: Everyone is ARTIST!
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home


related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false

```

## Link to the demo site and/or source repository

https://github.com/Peckystudios/PeckyPlayZone

**Comment by zhixuan666** [comment] 2021-06-03 10:08
```html
<!-- assets\icons\store.svg -->
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-building-store" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#9e9e9e" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <line x1="3" y1="21" x2="21" y2="21" />
  <path d="M3 7v1a3 3 0 0 0 6 0v-1m0 1a3 3 0 0 0 6 0v-1m0 1a3 3 0 0 0 6 0v-1h-18l2 -4h14l2 4" />
  <line x1="5" y1="21" x2="5" y2="10.85" />
  <line x1="19" y1="21" x2="19" y2="10.85" />
  <path d="M9 21v-4a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v4" />
</svg>
```
更改到这个

生成svg [tablericons](https://tablericons.com/)

**Comment by FarrelF** [comment] 2021-06-04 03:21
For Menu Icons, you can use [Tabler Icons](https://tablericons.com/) as used by this theme according to theme documentation about ["Add custom icon"](https://docs.stack.jimmycai.com/configuration/custom-menu#add-custom-icon), here below is the how:

1. Visit [Tabler Icons Website](https://tablericons.com) 
2. Search `building-store` (In case you're looking for Store Icon) 
3. Then, change the "Size" to `24px` and the "Color" with `currentColor` 
4. Click the icon to copy the SVG code
5. Paste it to your Favourite Text/Code Editor
6. Save as SVG (Or, you can just replace the existing old icon while Saving)
7. And, you're done!

For Open Menu as a New Tab, you can create file named `left.html` in `layouts/partials/sidebar` (In your [Root Site Folder](https://github.com/Peckystudios/PeckyPlayZone) of course, not in your [`themes`](https://github.com/Peckystudios/PeckyPlayZone/tree/main/themes) folder). Then, copy and paste the code below:

<details>
<summary>For `left.html` file</summary>

```html
<aside class="sidebar left-sidebar sticky">
    <button class="hamburger hamburger--spin" type="button" id="toggle-menu" aria-label="{{ T `toggleMenu` }}">
        <span class="hamburger-box">
            <span class="hamburger-inner"></span>
        </span>
    </button>

    <header class="site-info">
        {{ with .Site.Params.sidebar.avatar }}
            <figure class="site-avatar">
                {{ if not .local }}
                    <img src="{{ .src }}" width="300" height="300" class="site-logo" loading="lazy" alt="Avatar">
                {{ else }}
                    {{ $avatar := resources.Get (.src) }}
                    
                    {{ if $avatar }}
                        {{ $avatarResized := $avatar.Resize "300x" }}
                        <img src="{{ $avatarResized.RelPermalink }}" width="{{ $avatarResized.Width }}"
                            height="{{ $avatarResized.Height }}" class="site-logo" loading="lazy" alt="Avatar">
                    {{ else }}
                        {{ errorf "Failed loading avatar from %q" . }}
                    {{ end }}
                {{ end }}

                {{ with $.Site.Params.sidebar.emoji }}
                    <span class="emoji">{{ . }}</span>
                {{ end }}
            </figure>
        {{ end }}
        <h1 class="site-name"><a href="{{ .Site.BaseURL }}">{{ .Site.Title }}</a></h1>
        <h2 class="site-description">{{ .Site.Params.sidebar.subtitle }}</h2>
    </header>

    <ol class="menu" id="main-menu">
        {{ $currentPage := . }}
        {{ range .Site.Menus.main }}
        {{ $active := or (eq $currentPage.Title .Name) (or ($currentPage.HasMenuCurrent "main" .) ($currentPage.IsMenuCurrent "main" .)) }}

        <li {{ if $active }} class='current' {{ end }}>
            <a href='{{ .URL }}' {{ if eq .Params.NewTab true }}target="_blank"{{ end }} {{ if strings.HasPrefix .URL "http" }}rel="noopener"{{ end }}>
                {{ if .Pre }}
                    {{ partial "helper/icon" .Pre }}
                {{ end }}
                <span>{{- .Name -}}</span>
            </a>
        </li>
        {{ end }}

        {{ if (default false .Site.Params.colorScheme.toggle) }}
            <li id="dark-mode-toggle">
                {{ partial "helper/icon" "toggle-left" }}
                {{ partial "helper/icon" "toggle-right" }}
                <span>{{ T "darkMode" }}</span>
            </li>
        {{ end }}
    </ol>
</aside>
```
</details>

After paste the code, don't forget to save the file. 

In your Marokdown Front Matter, you can add `newtab` in `params` when using `menu.main` and set it to `true`. Just like this:

<details>
<summary>For your Front Matter</summary>

```md
menu:
    main: 
        url: https://www.rakuten.com.tw/shop/peckystudio/
        weight: -10
		params:
		    newtab: true
        pre: store
```
</details>

And then, save your Markdown file and see the changes. Hope this solution is helpful!

**Comment by Peckystudios** [comment] 2021-06-04 06:46
@zhixuan666 
@FarrelF 
Thank you very much!

Everything works very well!!

**Comment by FarrelF** [comment] 2021-06-07 06:42
If the problem is solved, then you can close this issue 🙂

**Closed** 2021-06-07 06:44 UTC

**Comment by CaiJimmy** [comment] 2021-06-12 07:58
Thanks to @FarrelF and @zhixuan666 

"Open Menu Link(s) in a New Tab" is something that I'd like to integrate into this theme. It requires a Hugo version upgrade (I think >= 0.79.0). But that version has broken something related to `jsconfig.json`, and my site can not compile with posterior versions.

It will be part of the theme once I get to fix my development environment.
